### ISSUE TITLE
Evol App Module - Scss

### ISSUE THREAD

**Issue by Nycolaide** [Nycolaide/manakit#21]
Scss 👍 

.m-app {
    display: flex;
    position: relative;
}

style :     transform-origin: center top 0px;  ?

**Comment by Nycolaide** [comment]
```css
.wrap {
    flex: 1 1 auto;
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    max-width: 100%;
    position: relative;
}
```
